name: Validate on Raspberry Pi

on:
  workflow_dispatch:  # Manual trigger

jobs:
  rpi-test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-14 cmake protobuf-compiler libprotobuf-dev time libomp-14-dev

      - name: Set up virtualenv and install NumPy
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install numpy

      - name: Initialize Submodules
        run: |
          git submodule update --init --recursive

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DENABLE_TIMING=ON -DENABLE_MEM_USAGE=ON -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cd build
          make -j2

      - name: Run MobileNet inference
        run: ./build/TinyONNX test_data/mobilenet_v2.onnx test_data/input_tensor.npy

      - name: Validate MobileNet output
        run: |
          source venv/bin/activate
          python3 tests/validate_mobilenet.py

      - name: Benchmark runtime
        run: /usr/bin/time -v ./build/TinyONNX test_data/mobilenet_v2.onnx test_data/input_tensor.npy
