name: Validate MobileNet

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-14 cmake libomp-14-dev

      - name: Install NumPy
        run: pip install numpy

      - name: Initialize Submodules
        run: |
          git submodule update --init --recursive

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cd build
          make -j$(nproc)

      - name: Run TinyONNX on MobileNet
        run: ./build/TinyONNX test_data/mobilenet_v2.onnx test_data/input_tensor.npy

      - name: Validate Output
        run: python3 tests/validate_mobilenet.py
